# Generated by Django 5.0.1 on 2024-01-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_alter_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sentiment_score',
            field=models.FloatField(default=0),
        ),
    ]
