# Generated by Django 5.0.1 on 2024-02-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_post_sentiment_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_deepfake',
        ),
        migrations.AddField(
            model_name='post',
            name='deep_fake_confidence',
            field=models.FloatField(default=0),
        ),
    ]
