# Generated by Django 5.0.1 on 2024-02-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_remove_post_is_deepfake_post_deep_fake_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_posted_from_offline',
            field=models.BooleanField(default=False),
        ),
    ]
