# Generated by Django 5.0.1 on 2024-03-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0010_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voice_comment',
            field=models.FileField(blank=True, null=True, upload_to='voice_comments/'),
        ),
    ]
