# Generated by Django 5.0.1 on 2024-03-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0011_comment_voice_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deep_fake_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deep_fake',
            field=models.BooleanField(default=False),
        ),
    ]
