# Generated by Django 5.0.1 on 2024-02-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_messagenotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageNotification',
        ),
    ]
