# Generated by Django 4.2.1 on 2023-07-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
