# Generated by Django 5.0.1 on 2024-01-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='overall_sentiment',
            field=models.FloatField(default=0.3),
        ),
    ]
