# Generated by Django 4.2.1 on 2023-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_userprofile_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(default=123412, max_length=6),
            preserve_default=False,
        ),
    ]
