# Generated by Django 4.2.7 on 2023-12-07 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentication', '0007_userprofile_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_warnings', models.IntegerField(default=0)),
                ('number_of_reports', models.IntegerField(default=0)),
                ('number_of_posts', models.IntegerField(default=0)),
                ('number_of_comments', models.IntegerField(default=0)),
                ('number_of_likes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_certificate', models.FileField(upload_to='certificates/')),
                ('experience_name', models.CharField(max_length=100)),
                ('experience_start_date', models.DateField()),
                ('experience_end_date', models.DateField()),
                ('experience_id', models.UUIDField(editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_name', models.CharField(max_length=100)),
                ('education_start_date', models.DateField()),
                ('education_end_date', models.DateField()),
                ('education_id', models.UUIDField(editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userEducation', models.ManyToManyField(blank=True, to='Authentication.usereducation')),
                ('userExperience', models.ManyToManyField(blank=True, to='Authentication.userexperience')),
            ],
        ),
    ]
