# Generated by Django 4.2.7 on 2023-12-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_userextras_userexperience_usereducation_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereducation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userexperience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userextras',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.DeleteModel(
            name='UserEducation',
        ),
        migrations.DeleteModel(
            name='UserExperience',
        ),
        migrations.DeleteModel(
            name='UserExtras',
        ),
    ]
