# Generated by Django 4.2.7 on 2023-12-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_remove_usereducation_user_remove_userexperience_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
