# Generated by Django 5.0.1 on 2024-02-21 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.CharField(default='false', max_length=50)),
                ('langauge', models.CharField(default='en', max_length=50)),
                ('message_notification', models.BooleanField(default=True)),
                ('friend_request_notification', models.BooleanField(default=True)),
                ('post_notification', models.BooleanField(default=True)),
                ('sync_post_for_offline', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
