# Generated by Django 5.0.1 on 2024-02-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserUtils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='langauge',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('np', 'np')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='dark_mode',
            field=models.CharField(choices=[('auto', 'auto'), ('light', 'light'), ('dark', 'dark')], default='auto', max_length=5),
        ),
    ]
