# Generated by Django 5.0.1 on 2024-02-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserUtils', '0002_remove_usersettings_langauge_usersettings_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='post_notification',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='post_comment_notification',
            field=models.CharField(choices=[('push', 'push'), ('app', 'app'), ('both', 'both'), ('none', 'none')], default='app', max_length=5),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='post_like_notification',
            field=models.CharField(choices=[('push', 'push'), ('app', 'app'), ('both', 'both'), ('none', 'none')], default='app', max_length=5),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='request_accepted_notification',
            field=models.CharField(choices=[('push', 'push'), ('app', 'app'), ('both', 'both'), ('none', 'none')], default='app', max_length=5),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='friend_request_notification',
            field=models.CharField(choices=[('push', 'push'), ('app', 'app'), ('both', 'both'), ('none', 'none')], default='app', max_length=5),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='message_notification',
            field=models.CharField(choices=[('push', 'push'), ('app', 'app'), ('both', 'both'), ('none', 'none')], default='app', max_length=5),
        ),
    ]
