# Generated by Django 4.2.7 on 2023-12-26 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='id',
        ),
        migrations.AddField(
            model_name='friends',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friends',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4bbbb6a4-0010-4993-b62f-f3a16404571b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
