# Generated by Django 4.2.7 on 2023-12-26 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserData', '0002_remove_friends_id_friends_sender_friends_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='user',
        ),
        migrations.AddField(
            model_name='friends',
            name='friend1',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='friend2',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='friend_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('676e8a0d-0c75-4a3e-a52d-07d31026d82d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
