# Generated by Django 5.0.1 on 2024-02-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0006_friendrequestnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequestNotification',
        ),
    ]
